DROP DATABASE IF EXISTS Userdb;
CREATE DATABASE Userdb;

CREATE TABLE user (
    id INT(10) NOT NULL,
    username VARCHAR(50) NOT NULL,
    password VARCHAR(255) NOT NULL
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=4 ;

CREATE TABLE fav (
    id INT(10) NOT NULL,
    username VARCHAR(50) NOT NULL,
    petid VARCHAR(255) NOT NULL
    PRIMARY KEY (id)
)
